# Generated by Django 5.1.5 on 2025-02-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_variacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacion',
            name='variacion_categoria',
            field=models.CharField(choices=[('color', 'color'), ('talla', 'talla')], max_length=100),
        ),
    ]
