# Generated by Django 5.2 on 2025-08-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_telefono'),
        ('tienda', '0003_alter_variacion_variacion_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoordenado',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productoordenado',
            name='size',
        ),
        migrations.AlterField(
            model_name='productoordenado',
            name='variaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.variacion'),
        ),
    ]
