# Generated by Django 5.2 on 2025-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_productoordenado_color_and_more'),
        ('tienda', '0003_alter_variacion_variacion_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoordenado',
            name='variaciones',
        ),
        migrations.AddField(
            model_name='productoordenado',
            name='variaciones',
            field=models.ManyToManyField(blank=True, to='tienda.variacion'),
        ),
    ]
