# Generated by Django 5.1.5 on 2025-02-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('tienda', '0003_alter_variacion_variacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_item',
            name='variaciones',
            field=models.ManyToManyField(blank=True, to='tienda.variacion'),
        ),
    ]
