# Generated by Django 5.2 on 2025-08-17 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_carrito_item_variaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrito_item',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito'),
        ),
    ]
